<?php
/**
 * Page Cache Ultimate, Page Cache standard and Speed pack are powered by Jpresta (jpresta . com)
 *
 * @author    Jpresta
 * @copyright Jpresta
 * @license   See the license of this module in file LICENSE.txt, thank you.
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

/**
 * Implements getJprestaModelObjectClassName() and getJprestaModelObjectId() to enable the HTML cache provided by the
 * module Page Cache Ultimate created by jpresta.com
 */
class smartblogCategoryModuleFrontControllerOverride extends smartblogCategoryModuleFrontController
{
    /**
     * @return string The ObjectModel class name to be used by Page Cache Ultimate module to refresh the cache of pages generated by this controller
     */
    public static function getJprestaModelObjectClassName()
    {
        return 'BlogCategory';
    }

    /**
     * @return int|null The ID of the current ObjectModel (if any) to be used by Page Cache Ultimate module to refresh the cache of pages generated by this controller
     */
    public function getJprestaModelObjectId()
    {
        $smartblogurlpattern = (int) Configuration::get('smartblogurlpattern');

        switch ($smartblogurlpattern) {
            case 1:
                $SmartBlog   = new smartblog();
                $slug        = Tools::getValue('slug');
                $id_category = (int) $SmartBlog->categoryslug2id($slug);
                break;
            case 2:
            default:
                $id_category = (int) Tools::getValue('id_category');
        }

        if ($id_category > 0) {
            $postObj = new BlogCategory($id_category);
            if (Validate::isLoadedObject($postObj)) {
                return $id_category;
            }
        }

        return null;
    }
}
