<?php
/**
 * Page Cache Ultimate, Page Cache standard and Speed pack are powered by Jpresta (jpresta . com)
 *
 * @author    Jpresta
 * @copyright Jpresta
 * @license   See the license of this module in file LICENSE.txt, thank you.
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

use AdvancedSearch\Models\Seo;
use AdvancedSearch\SearchEngineUtils;

/**
 * Implements getJprestaModelObjectClassName() and getJprestaModelObjectId() to enable the HTML cache provided by the
 * module Page Cache Ultimate created by jpresta.com
 */
class pm_advancedsearch4seoModuleFrontControllerOverride extends pm_advancedsearch4seoModuleFrontController
{
    /**
     * @return string The ObjectModel class name to be used by Page Cache Ultimate module to refresh the cache of pages generated by this controller
     */
    public static function getJprestaModelObjectClassName()
    {
        if (class_exists('AdvancedSearch\Models\Seo')) {
            return 'AdvancedSearch\Models\Seo';
        }
        else if (class_exists('AdvancedSearchSeoClass')) {
            return 'AdvancedSearchSeoClass';
        }
    }

    /**
     * @return int|null The ID of the current ObjectModel (if any) to be used by Page Cache Ultimate module to refresh the cache of pages generated by this controller
     */
    public function getJprestaModelObjectId()
    {
        $id_seo = (int)Tools::getValue('id_seo');
        if (class_exists('AdvancedSearch\Models\Seo')) {
            if ($id_seo && ($seoObj = new Seo($id_seo)) && Validate::isLoadedObject($seoObj)) {
                return $id_seo;
            }
        }
        else if (class_exists('AdvancedSearchSeoClass')) {
            if ($id_seo && ($seoObj = new AdvancedSearchSeoClass($id_seo)) && Validate::isLoadedObject($seoObj)) {
                return $id_seo;
            }
        }
        return null;
    }

    /**
     * List all URLs generated by this controller for the current shop context and the specified language.
     * This is used by the Jresta-Cache-Warmer service to generate the cache of these pages.
     * @param $id_lang int ID of the language
     * @return string[] All URLs to warmup
     */
    public static function getJprestaAllURLs($id_lang) {
        $context = Context::getContext();
        $urls = [];
        if (class_exists('SearchEngineUtils') && method_exists('SearchEngineUtils', 'getAllSearchs')
            && class_exists('Seo') && method_exists('Seo', 'getSeoSearchs')) {
            $searchEngines = SearchEngineUtils::getAllSearchs((int)$id_lang, true);
            if ($searchEngines && is_array($searchEngines)) {
                foreach ($searchEngines as $searchEngine) {
                    $id_search = (int)$searchEngine['id_search'];
                    $seoSearchs = Seo::getSeoSearchs($id_lang, false, $id_search);
                    if ($seoSearchs && is_array($seoSearchs)) {
                        foreach ($seoSearchs as $seoSearch) {
                            $urls[] = $context->link->getModuleLink('pm_advancedsearch4', 'seo', [
                                'id_seo' => (int)$seoSearch['id_seo'],
                                'seo_url' => $seoSearch['seo_url'],
                            ], null, (int)$id_lang);
                        }
                    }
                }
            }
        }
        return $urls;
    }

    /**
     * An estimated number of URLs that will be returned by self::getJprestaAllURLs() for the current shop context.
     * Since we don't have the id_lang parameter we recommend to return the number of URLs for the language that have
     * the most URLs.
     * @return int The estimated number of URLs to warmup for the current shop context
     */
    public static function getJprestaAllURLsCount() {
        $urlCount = 0;
        if (class_exists('SearchEngineUtils') && method_exists('SearchEngineUtils', 'getAllSearchs')
            && class_exists('Seo') && method_exists('Seo', 'getSeoSearchs')) {
            $searchEngines = SearchEngineUtils::getAllSearchs((int)Configuration::get('PS_LANG_DEFAULT'), true);
            if ($searchEngines && is_array($searchEngines)) {
                foreach ($searchEngines as $searchEngine) {
                    $id_search = (int)$searchEngine['id_search'];
                    $seoSearchs = Seo::getSeoSearchs((int)Configuration::get('PS_LANG_DEFAULT'), false, $id_search);
                    if ($seoSearchs && is_array($seoSearchs)) {
                        $urlCount += count($seoSearchs);
                    }
                }
            }
        }
        return $urlCount;
    }
}
