<?php
/**
 * Page Cache Ultimate, Page Cache standard and Speed pack are powered by Jpresta (jpresta . com)
 *
 * @author    Jpresta
 * @copyright Jpresta
 * @license   See the license of this module in file LICENSE.txt, thank you.
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

/**
 * Implements getJprestaModelObjectClassName() and getJprestaModelObjectId() to enable the HTML cache provided by the
 * module Page Cache Ultimate created by jpresta.com
 */
class smartblogDetailsModuleFrontControllerOverride extends smartblogDetailsModuleFrontController
{
    /**
     * @return string The ObjectModel class name to be used by Page Cache Ultimate module to refresh the cache of pages generated by this controller
     */
    public static function getJprestaModelObjectClassName()
    {
        return 'SmartBlogPost';
    }

    /**
     * @return int|null The ID of the current ObjectModel (if any) to be used by Page Cache Ultimate module to refresh the cache of pages generated by this controller
     */
    public function getJprestaModelObjectId()
    {
        $smartblogUrlPattern = (int) Configuration::get('smartblogurlpattern');
        $hookValue = Tools::getValue('hook');
        $idPost = null;

        if ($hookValue === 'extended') {
            $idPost = (int) Tools::getValue('id_post');
        } else {
            switch ($smartblogUrlPattern) {
                case 1:
                    $slug = Tools::getValue('slug');
                    $smartBlog = new smartblog();
                    $idPost = (int) $smartBlog->slug2id($slug);
                    break;

                case 2:
                case 3:
                default:
                    $idPost = (int) Tools::getValue('id_post');
                    break;
            }
        }

        if ($idPost > 0) {
            $postObj = new SmartBlogPost($idPost);
            if (Validate::isLoadedObject($postObj)) {
                return $idPost;
            }
        }

        return null;
    }
}
