<?php
/**
 * Copyright ETS Software Technology Co., Ltd
 *
 * NOTICE OF LICENSE
 *
 * This file is not open source! Each license that you purchased is only available for 1 website only.
 * If you want to use this file on more websites (or projects), you need to purchase additional licenses.
 * You are not allowed to redistribute, resell, lease, license, sub-license or offer our resources to any third party.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future.
 *
 * @author ETS Software Technology Co., Ltd
 * @copyright  ETS Software Technology Co., Ltd
 * @license    Valid for 1 website (or project) for each purchase of license
 */
if (!defined('_PS_VERSION_')) {
    exit;
}
require_once __DIR__ . '/traits/EtsSeoTranslationTrait.php';
require_once __DIR__ . '/traits/EtsSeoGetModuleTrait.php';
require_once __DIR__ . '/interfaces/EtsSeoAnalyzeModelInterface.php';


/**
 * Class AbstractEtsSeoAnalyzableModel
 *
 * @mixin \ObjectModelCore
 *
 * @since 2.6.4
 */
abstract class AbstractEtsSeoAnalyzableModel extends ObjectModel implements EtsSeoAnalyzeModelInterface
{
    use EtsSeoTranslationTrait;
    use EtsSeoGetModuleTrait;

    /**
     * {@inheritDoc}
     */
    public $seo_score;
    public $readability_score;
    public $score_analysis;
    public $content_analysis;
    protected $seo_score_structure = [
        'outbound_link',
        'internal_link',
        'text_length',
        'keyphrase_length',
        'keyphrase_in_subheading',
        'keyphrase_in_title',
        'keyphrase_in_page_title',
        'keyphrase_in_intro',
        'keyphrase_density',
        'image_alt_attribute',
        'seo_title_width',
        'meta_description_length',
        'keyphrase_in_meta_desc',
        'keyphrase_in_slug',
        'minor_keyphrase_in_content',
        'minor_keyphrase_in_title',
        'minor_keyphrase_in_desc',
        'minor_keyphrase_in_page_title',
        'minor_keyphrase_acceptance',
        'single_h1',
        'keyphrase_density_individual',
        'minor_keyphrase_in_content_individual',
        'minor_keyphrase_length',
    ];

    protected $readability_score_structure = [
        'not_enough_content',
        'sentence_length',
        'flesch_reading_ease',
        'paragraph_length',
        'consecutive_sentences',
        'subheading_distribution',
        'transition_words',
        'passive_voice',
    ];


    public $allow_search;
    public $allow_flw_link;

    public function __construct($id = null, $id_lang = null, $id_shop = null, $translator = null)
    {
        parent::__construct($id, $id_lang, $id_shop, $translator);
        if (!$this->id) {
            if ($id_lang) {
                $this->id_lang = $id_lang;
            }
            if ($id_shop) {
                $this->id_shop = $id_shop;
            }
        }
    }


    public function save($null_values = false, $auto_date = true)
    {
        if (property_exists($this, 'allow_search') && $this->allow_search == null)
            $this->allow_search = 2;
        if (property_exists($this, 'allow_flw_link') && $this->allow_flw_link == null)
            $this->allow_flw_link = 1;
        return parent::save($null_values, $auto_date); // TODO: Change the autogenerated stub
    }
    public static function findOneByRelationId($id, $idLang = null, $idShop = null)
    {
        $query = (new DbQuery())->select(static::$definition['primary'])->from(static::$definition['table']);
        $query->where(sprintf('%s = %d', bqSQL(static::getRelationIdColumnName()), $id));
        if ($idLang) {
            $query->where(sprintf('id_lang = %d', (int) $idLang));
        }
        if ($idShop) {
            $query->where(sprintf('id_shop = %d', (int) $idShop));
        }
        return  (int) Db::getInstance(_PS_USE_SQL_SLAVE_)->getValue($query);
    }
    public function parseContentAnalysis($contentAnalysis)
    {
        foreach ($contentAnalysis as $idLang => $rules) {
            if ($idLang != $this->id_lang) {
                unset($contentAnalysis[$idLang]);
                continue;
            }
            foreach ($rules as $keyRule => &$rule) {
                if (false === strpos($keyRule, '_problem')) {
                    if (isset($rule['text']) && !Validate::isCleanHtml($rule['text'])) {
                        $rule['text'] = '';
                    }
                } else {
                    if (!empty($rule)) {
                        foreach ($rule as $idx => $item) {
                            if (!Validate::isCleanHtml($item)) {
                                $rule[$idx] = '';
                            }
                        }
                    }
                }
            }
            unset($rule);
        }

        return $contentAnalysis;
    }
    public function setSeoScore($seo_scores = [], $readability_scores = [], array $content_analysis = [])
    {
        $seo_score = 0;
        $readability_score = 0;
        $scoreAnalysis = [
            'seo_score' => [],
            'readability_score' => [],
        ];
        if (!$seo_scores) {
            $seo_scores = [];
        }
        if (!$readability_scores) {
            $readability_scores = [];
        }
        if (property_exists($this, 'seo_score_structure') && is_array($this->seo_score_structure)) {
            foreach ($this->seo_score_structure as $ruleKey) {
                if (!isset($seo_scores[$ruleKey])) {
                    $seo_scores[$ruleKey] = [];
                }
                if (!isset($seo_scores[$ruleKey][$this->id_lang])) {
                    $seo_scores[$ruleKey][$this->id_lang] = 0;
                }
            }
        }
        if (property_exists($this, 'readability_score_structure') && is_array($this->readability_score_structure)) {
            foreach ($this->readability_score_structure as $ruleKey) {
                if (!isset($readability_scores[$ruleKey])) {
                    $readability_scores[$ruleKey] = [];
                }
                if (!isset($readability_scores[$ruleKey][$this->id_lang])) {
                    $readability_scores[$ruleKey][$this->id_lang] = 0;
                }
            }
        }
        
        // Count applicable SEO rules (exclude N/A scores)
        $applicable_seo_rules = 0;
        if (is_array($seo_scores)) {
            foreach ($seo_scores as $keyRule => $rule) {
                // Only process rules that are defined in the structure
                if (!in_array($keyRule, $this->seo_score_structure)) {
                    continue;
                }
                
                if (isset($rule[$this->id_lang])) {
                    $scoreAnalysis['seo_score'][$keyRule] = $rule[$this->id_lang];
                    // Skip N/A scores (-999) - they should not be counted in total
                    if ((int) $rule[$this->id_lang] !== -999) {
                        $seo_score += (int) $rule[$this->id_lang];
                        $applicable_seo_rules++;
                    }
                } elseif (!isset($scoreAnalysis['seo_score'][$keyRule])) {
                    $scoreAnalysis['seo_score'][$keyRule] = 0;
                    if (class_exists('PrestaShopLogger')) {
                        PrestaShopLogger::addLog(sprintf('[ets_seo] Missing seo rule "%s" for lang %d. Data: %s', $keyRule, (int) $this->id_lang, json_encode($rule)), 1, null, static::class, $this->id);
                    }
                }
            }
        }
        
        // Count applicable Readability rules (exclude N/A scores)
        $applicable_readability_rules = 0;
        if (is_array($readability_scores)) {
            foreach ($readability_scores as $keyRule => $rule) {
                // Only process rules that are defined in the structure
                if (!in_array($keyRule, $this->readability_score_structure)) {
                    continue;
                }
                
                if (isset($rule[$this->id_lang])) {
                    $scoreAnalysis['readability_score'][$keyRule] = $rule[$this->id_lang];
                    // Skip N/A scores (-999) - they should not be counted in total
                    if ((int) $rule[$this->id_lang] !== -999) {
                        $readability_score += (int) $rule[$this->id_lang];
                        $applicable_readability_rules++;
                    }
                } elseif (!isset($scoreAnalysis['readability_score'][$keyRule])) {
                    $scoreAnalysis['readability_score'][$keyRule] = 0;
                    if (class_exists('PrestaShopLogger')) {
                        PrestaShopLogger::addLog(sprintf('[ets_seo] Missing readability rule "%s" for lang %d. Data: %s', $keyRule, (int) $this->id_lang, json_encode($rule)), 1, null, static::class, $this->id);
                    }
                }
            }
        }
        
        // Store the actual number of applicable rules
        $scoreAnalysis['total_applicable_seo_rules'] = $applicable_seo_rules;
        $scoreAnalysis['total_applicable_readability_rules'] = $applicable_readability_rules;
        
        $this->seo_score = $seo_score;
        $this->readability_score = $readability_score;
        $this->score_analysis = json_encode($scoreAnalysis);
        if (isset($content_analysis[$this->id_lang]) && is_array($content_analysis[$this->id_lang])) {
            $decodedContentAnalysis = Ets_Seo::decodeBase64InContentAnalysis([$this->id_lang => $content_analysis[$this->id_lang]]);
            $this->content_analysis = json_encode($decodedContentAnalysis[$this->id_lang] ?? [], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        } else {
            $this->content_analysis = json_encode([], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        }

        return $this;
    }
}
