<?php

class SteRobotsManager
{
    /**
     * Update robots.txt to include sitemap links
     * 
     * @param string $robotsPath Path to robots.txt
     * @param array $sitemapLinks Array of absolute URLs to sitemaps
     */
    public function updateRobotsTxt($robotsPath, $sitemapLinks)
    {
        $content = '';
        if (file_exists($robotsPath)) {
            $content = file_get_contents($robotsPath);
        }

        // Remove old STE Sitemap blocks to avoid duplication
        $content = preg_replace('/# STE-SITEMAP-START(.*?)# STE-SITEMAP-END/s', '', $content);
        $content = trim($content);

        $newBlock = "\n\n# STE-SITEMAP-START\n";
        $newBlock .= "# Automaticaly generated by steseositemap module\n";
        foreach ($sitemapLinks as $link) {
            $newBlock .= "Sitemap: " . $link . "\n";
        }
        $newBlock .= "# STE-SITEMAP-END\n";

        return file_put_contents($robotsPath, $content . $newBlock);
    }

    /**
     * Check if robots.txt has critical issues
     */
    public function analyze($robotsPath)
    {
        $issues = [];
        if (!file_exists($robotsPath)) {
            $issues[] = ['level' => 'critical', 'msg' => 'robots.txt is missing'];
            return $issues;
        }

        $content = file_get_contents($robotsPath);
        
        if (strpos($content, 'Disallow: /') !== false && strpos($content, 'Disallow: / ') === false) {
             // Heuristic: Disallow: / (without space) likely blocks everything, check context
             // Actually 'Disallow: /' blocks everything.
             // We need to be careful not to flag "Disallow: /admin" as blocking root.
             if (preg_match('/^Disallow:\s*\/$/m', $content)) {
                 $issues[] = ['level' => 'critical', 'msg' => 'Your robots.txt blocks the entire site (Disallow: /)'];
             }
        }

        if (strpos($content, 'Sitemap:') === false) {
            $issues[] = ['level' => 'warning', 'msg' => 'No Sitemap directive found in robots.txt'];
        }

    /**
     * Remove legacy sitemap entries (like 1_index_sitemap.xml)
     */
    public function cleanLegacySitemaps($robotsPath)
    {
        if (!file_exists($robotsPath)) return false;
        
        $content = file_get_contents($robotsPath);
        
        // Remove standard PS sitemap lines
        // e.g. Sitemap: https://domain.com/1_index_sitemap.xml
        $content = preg_replace('/^Sitemap:.*_index_sitemap\.xml.*$/m', '', $content);
        
        // Remove empty lines created
        $content = preg_replace("/(^[\r\n]*|[\r\n]+)[\s\t]*[\r\n]+/", "\n", $content);
        
        return file_put_contents($robotsPath, trim($content));
    }
}
